### ISSUE TITLE
Export values and seeds

### ISSUE THREAD

**Issue by tdewolff** [dgryski/go-mph#4]
Would it be possible to export `values` and `seeds` ? Might be related to #2, but I'm using `go generate` to construct hash tables in https://github.com/tdewolff/hasher and I need those values to serialize to `.go`.

**Comment by dgryski** [comment]
I was actually thinking of adding code generation here.  I will accept a PR to make serialization/de-serialization easier.

**Comment by dgryski** [comment]
Merged https://github.com/dgryski/go-mph/pull/6
